pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo '++++++++++++++++++++++++ Main Branch inside +++++++++  99999999999999999999999 +++++++++++++++++++++'
            }
        }
    }
}
