xpipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo '++++++++++++++++++++++++ Main Branch inside +++++++++xcc +++++++++++++++++++++'
            }
        }
    }
}
